#r "../src/Geb.UI.D2D/bin/Debug/netcoreapp3.0/Geb.UI.dll"
#r "../src/Geb.UI.D2D/bin/Debug/netcoreapp3.0/Geb.UI.D2D.dll"
#r "../src/Geb.UI.D2D/bin/Debug/netcoreapp3.0/ExCSS.dll"
#r "../src/Geb.UI.Plot/bin/Debug/netcoreapp3.0/Geb.UI.Plot.dll"
#r "nuget: Geb.Image, 2.0.1"
#r "nuget: SharpDX, 4.2.0"
#r "nuget: SharpDX.Direct2D1, 4.2.0"
#r "nuget: SharpDX.Direct3D11, 4.2.0"
#r "nuget: SharpGen.Runtime, 1.1.2"