// #r "../src/NScript.UI.D2D/bin/Debug/net6.0/NScript.UI.dll"
// #r "../src/NScript.UI.D2D/bin/Debug/net6.0/NScript.UI.D2D.dll"
// #r "../src/NScript.UI.D2D/bin/Debug/net6.0/ExCSS.dll"
// #r "../src/NScript.Plot/bin/Debug/net6.0/NScript.Plot.dll"

// #r "nuget: Geb.Image, 6.0.5"
// #r "nuget: SharpDX, 4.2.0"
// #r "nuget: SharpDX.Direct2D1, 4.2.0"
// #r "nuget: SharpDX.Direct3D11, 4.2.0"
// #r "nuget: SharpGen.Runtime, 1.1.2"